In [50]:
# 音源方向推定

# 理論的。実機使いたいなら機械学習にした方がいい。。


Mdeg = 15  # マイク 間隔(deg)
Mrad = 0.5    # マイク半径

Sdeg = 15   # 音源 間隔(deg)
Srad = 3       # 音源半径


In [51]:
import numpy as np
import math
import matplotlib.pyplot as plt
import sys
import scipy.io.wavfile as audio
# import scikits.audiolab の方が機能多いっぽい..

In [52]:
# 円形に配置されたマイクを仮定。中は中空

Mpos = np.zeros([round(360/Mdeg)+1, 3])
# print(Mpos[1,:])
for deg in range(0, 360, Mdeg):
    Mpos[round(deg/Mdeg),:]=[Mrad*np.cos(deg/180*np.pi),Mrad*np.sin(deg/180*np.pi),0]
    # print(Mpos[round(deg/Mdeg),:])

# 円形に配置された音源を仮定。中は中空
Spos = np.zeros([round(360/Sdeg)+1, 3])
for deg in range(0, 360, Sdeg):
    Spos[round(deg/Sdeg),:]=[Srad*np.cos(deg/180*np.pi),Srad*np.sin(deg/180*np.pi),0]

# 自由音場での伝達関数 G=


In [53]:
print(Spos)

[[ 3.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 2.89777748e+00  7.76457135e-01  0.00000000e+00]
 [ 2.59807621e+00  1.50000000e+00  0.00000000e+00]
 [ 2.12132034e+00  2.12132034e+00  0.00000000e+00]
 [ 1.50000000e+00  2.59807621e+00  0.00000000e+00]
 [ 7.76457135e-01  2.89777748e+00  0.00000000e+00]
 [ 1.83697020e-16  3.00000000e+00  0.00000000e+00]
 [-7.76457135e-01  2.89777748e+00  0.00000000e+00]
 [-1.50000000e+00  2.59807621e+00  0.00000000e+00]
 [-2.12132034e+00  2.12132034e+00  0.00000000e+00]
 [-2.59807621e+00  1.50000000e+00  0.00000000e+00]
 [-2.89777748e+00  7.76457135e-01  0.00000000e+00]
 [-3.00000000e+00  3.67394040e-16  0.00000000e+00]
 [-2.89777748e+00 -7.76457135e-01  0.00000000e+00]
 [-2.59807621e+00 -1.50000000e+00  0.00000000e+00]
 [-2.12132034e+00 -2.12132034e+00  0.00000000e+00]
 [-1.50000000e+00 -2.59807621e+00  0.00000000e+00]
 [-7.76457135e-01 -2.89777748e+00  0.00000000e+00]
 [-5.51091060e-16 -3.00000000e+00  0.00000000e+00]
 [ 7.76457135e-01 -2.89777748e+